---
  - name: remove old sources.list file
    command: rm /etc/apt/sources.list

  - name: add new sources.list file
    copy:
      src: sources.list
      dest: /etc/apt/sources.list

  - name: apt-get update
    command: apt-get update
    ignore_errors: true

  - name: install apt-transport-https curl
    apt:
      name: 
       - apt-transport-https
       - curl
       - ca-certificates
       - gnupg
       - lsb-release
    ignore_errors: yes

  - name: download google cloud key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /tmp/docker-key.gpg

  - name: Add Docker's official GPG key
    command: apt-key add /tmp/docker-key.gpg

  - name: get architecture
    command: dpkg --print-architecture
    register: architecture
  - name: set up the stable repository
    command: | 
      echo "deb [arch={{ architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

  - name: apt-get update
    command: apt-get update
    ignore_errors: true

  - name: install docker
    apt:
      name:
        - docker.io

  - name: download google cloud key
    get_url:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      dest: /tmp/apt-key.gpg

  - name: add google cloud key
    command: apt-key add /tmp/apt-key.gpg

  
  - name: apt-get update
    command: apt-get update
    ignore_errors: true

  - name: install kubelet kubeadm kubectl
    apt:
      name:
        - kubectl
        - kubelet
        - kubeadm
      state: latest

  - name: reset kubeadm (make sure to reset kube conf in all host if a config already exist to avoid issue config already exist when trying to init master node or join a cluster)
    command: kubeadm reset -f