---
  - name: install apt-transport-https curl
    apt:
      name: 
       - apt-transport-https
       - curl
       - software-properties-common
      update_cache: yes
  - name: download google cloud key
    get_url:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      dest: /tmp/apt-key.gpg
  - name: add google cloud key
    command: apt-key add /tmp/apt-key.gpg
  - name: check if key add correctly
    command: apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
  - name: apt-get update
    apt:
      update_cache: yes
  - name: install kubelet kubeadm kubectl and docker
    apt:
      name:
        - kubectl
        - kubelet
        - kubeadm
        - docker.io
      state: latest

  - name: reset kubeadm (make sure to reset kube conf in all host if a config already exist to avoid issue config already exist when trying to init master node or join a cluster)
    command: kubeadm reset -f